module.exports = {
    USER_REPLACE:            'USER_REPLACE',
    GET_TRAINING_GROUPS:     'GET_TRAINING_GROUPS',
    GET_TEAMS:               'GET_TEAMS',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILED:  'FORGOT_PASSWORD_FAILED',
    SIGN_UP_SUCCESS:         'SIGN_UP_SUCCESS',
    SIGN_UP_FAILED:          'SIGN_UP_FAILED',
    UPDATE_TRAINING_GROUPS:  'UPDATE_TRAINING_GROUPS',
    UPDATE_REGIMEN:          'UPDATE_REGIMEN',
    SIDEMENU_TOGGLE:         'SIDEMENU_TOGGLE',
    SIDEMENU_OPEN:           'SIDEMENU_OPEN',
    SIDEMENU_CLOSE:          'SIDEMENU_CLOSE',
    ADD_TG:                  'ADD_TG',
    EDIT_TG:                 'EDIT_TG',
    REMOVE_TG:               'REMOVE_TG',
    ADD_R:                   'ADD_R',
    EDIT_R:                  'EDIT_R',
    REMOVE_R:                'REMOVE_R',
    ADD_A:                   'ADD_A',
    EDIT_A:                  'EDIT_A',
    REMOVE_A:                'REMOVE_A',
    UPSERT_ACCESSORY:        'UPSERT_ACCESSORY',
};
