# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# target 'Fathom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fathom

  # target 'FathomTests' do
  #   inherit! :search_paths
    # Pods for testing
  # end

# end

use_frameworks!

target 'Fathom' do
  pod 'SwiftyJSON', git: 'https://github.com/IBM-Swift/SwiftyJSON.git'
  pod 'Charts', git: 'https://github.com/danielgindi/Charts.git'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
